// SPDX-License-Identifier: GPL-3.0-only

//! WMDE: turning a schema group into widgets.
//!
//! Every control here is one of the ones Settings already uses elsewhere, reached
//! through `widget::settings` - no bespoke metrics, no hand-written padding. A page
//! built from a third-party schema has to be indistinguishable from a page written in
//! Rust, and the only way to keep that true through future changes to
//! `.doc/appearance` is to own no measurements of our own.

use super::Message;
use super::schema::model::{ChoiceStyle, Control, Group, Row, Setting};
use super::store;
use cosmic::widget::list::list_column::IntoListItem;
use cosmic::widget::{column, dropdown, settings, text};
use cosmic::{Apply, Element};
use cosmic_settings_page as page;

/// Render one group as one settings card.
pub fn group<'a>(
    group: &'a Group,
    values: &'a [Option<String>],
    entity: page::Entity,
) -> Element<'a, crate::pages::Message> {
    let mut section = settings::section().title(group.title.as_str());

    for row in &group.rows {
        section = match row {
            Row::Note(text) => section.add(text::caption(text.as_str())),

            Row::Setting(setting) => match &setting.control {
                Control::Toggle => section.add(toggle(setting, values, entity)),

                Control::Choice { items, style } if *style == ChoiceStyle::Dropdown => {
                    section.add(choice_dropdown(setting, items, values, entity))
                }

                Control::Choice { items, .. } => {
                    // A radio group needs its own label: the card is titled after the
                    // group, which may hold more than this one question.
                    let mut section = section.add(heading(setting));
                    for (index, item) in items.iter().enumerate() {
                        section = section.add(choice_radio(setting, items, index, item, values, entity));
                    }
                    section
                }
            },
        };
    }

    section.into()
}

fn toggle<'a>(
    setting: &'a Setting,
    values: &'a [Option<String>],
    entity: page::Entity,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let is_on = current(setting, values)
        .and_then(store::as_bool)
        .unwrap_or(false);
    let slot = setting.slot;

    labelled(setting).toggler(is_on, move |value| {
        Message::Toggle {
            page: entity,
            slot,
            value,
        }
        .into()
    })
}

/// An item builder carrying the setting's label and, if it has one, its description.
///
/// `Item::description` is generated by `derive_setters` with `strip_option`, so there is
/// no `_maybe` form to pass an `Option` to.
fn labelled(setting: &Setting) -> settings::item::Item<'_, crate::pages::Message> {
    let item = settings::item::builder(setting.label.as_str());

    match setting.description.as_deref() {
        Some(description) => item.description(description),
        None => item,
    }
}

fn heading(setting: &Setting) -> Element<'_, crate::pages::Message> {
    column::with_capacity(2)
        .spacing(2)
        .push(text::heading(setting.label.as_str()))
        .push_maybe(setting.description.as_deref().map(text::caption))
        .into()
}

fn choice_radio<'a>(
    setting: &'a Setting,
    items: &'a [super::schema::model::ChoiceItem],
    index: usize,
    item: &'a super::schema::model::ChoiceItem,
    values: &'a [Option<String>],
    entity: page::Entity,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let slot = setting.slot;

    settings::item::builder(item.label.as_str()).radio(index, selected(setting, items, values), move |item| {
        Message::Choose {
            page: entity,
            slot,
            item,
        }
        .into()
    })
}

fn choice_dropdown<'a>(
    setting: &'a Setting,
    items: &'a [super::schema::model::ChoiceItem],
    values: &'a [Option<String>],
    entity: page::Entity,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let slot = setting.slot;
    // Owned, not borrowed: `popup_dropdown` requires `S: 'static` because the popup
    // surface outlives this view.
    let labels: Vec<String> = items.iter().map(|item| item.label.clone()).collect();

    // `popup_dropdown`, not `dropdown`: the settings column is 800 points wide at most,
    // and a plain dropdown clips its list inside it.
    let control = dropdown::popup_dropdown(
        labels,
        selected(setting, items, values),
        move |item| {
            Message::Choose {
                page: entity,
                slot,
                item,
            }
            .into()
        },
        cosmic::iced::window::Id::RESERVED,
        |action| crate::pages::Message::AppletSettings(Message::Surface(action)),
        crate::app::Message::PageMessage,
    );

    labelled(setting).control(control)
}

/// The value in force: what the config holds, else what the schema declares.
///
/// Falling back to the schema default matters on a machine where the applet has never
/// run and its package installed no defaults - without it every control would render
/// "off" while the applet itself uses something else.
fn current<'a>(setting: &'a Setting, values: &'a [Option<String>]) -> Option<&'a str> {
    values
        .get(setting.slot)
        .and_then(Option::as_deref)
        .or(setting.default.as_deref())
}

/// Which option is in force, if any.
///
/// A value outside the schema's list selects nothing. That is deliberate: the applet
/// may accept more than the schema chose to expose, and quietly snapping the display to
/// the nearest listed option would misreport what is actually configured.
fn selected(
    setting: &Setting,
    items: &[super::schema::model::ChoiceItem],
    values: &[Option<String>],
) -> Option<usize> {
    let value = current(setting, values)?;
    items
        .iter()
        .position(|item| store::same_value(&item.value, value))
}

/// A page body that says something instead of showing controls: an applet that ships no
/// schema, or one whose schema this build is too old to read.
///
/// Takes the text by value rather than by reference because the section closure that
/// calls it owns the string, and a view function may only borrow from its arguments.
pub fn message(text: String) -> Element<'static, crate::pages::Message> {
    text::body(text)
        .apply(cosmic::widget::container)
        .center_x(cosmic::iced::Length::Fill)
        .into()
}
