// SPDX-License-Identifier: GPL-3.0-only

//! WMDE: turning a schema group into widgets.
//!
//! Every control here is one of the ones Settings already uses elsewhere, reached
//! through `widget::settings` - no bespoke metrics, no hand-written padding. A page
//! built from a third-party schema has to be indistinguishable from a page written in
//! Rust, and the only way to keep that true through future changes to
//! `.doc/appearance` is to own no measurements of our own.

use super::Message;
use super::applet::Page;
use super::schema::model::{
    ChoiceItem, ChoiceStyle, Control, Group, Number, Row, Setting, Slider, TextField,
};
use super::store;
use cosmic::iced::{Alignment, Length};
use cosmic::widget::list::list_column::IntoListItem;
use cosmic::widget::{column, dropdown, row, settings, slider, text, toggler};
use cosmic::{Apply, Element, theme, widget};
use cosmic_settings_page as page;

/// Render one group as one settings card.
pub fn group<'a>(
    binder: &'a page::Binder<crate::pages::Message>,
    group: &'a Group,
    page: &'a Page,
) -> Element<'a, crate::pages::Message> {
    let mut section = settings::section().title(group.title.as_str());

    for row in &group.rows {
        section = match row {
            Row::Note(text) => section.add(text::caption(text.as_str())),

            // A link to a page this build does not have - a feature compiled out - is
            // dropped rather than drawn dead: a chevron that goes nowhere is worse than
            // a row that was never there.
            Row::Link {
                page: target,
                label,
            } => match find_page(binder, target) {
                Some(entity) => section.add(crate::widget::go_next_item(
                    label.as_str(),
                    crate::pages::Message::Page(entity),
                )),
                None => section,
            },

            Row::External { exec, label } => section.add(external(exec, label, page)),

            Row::Setting(setting) => match &setting.control {
                Control::Toggle => section.add(toggle(setting, page)),

                Control::Choice { items, style } if *style == ChoiceStyle::Dropdown => {
                    section.add(choice_dropdown(setting, items, page))
                }

                Control::Choice { items, .. } => {
                    // A radio group needs its own label: the card is titled after the
                    // group, which may hold more than this one question.
                    let mut section = section.add(heading(setting));
                    for (index, item) in items.iter().enumerate() {
                        section = section.add(choice_radio(setting, items, index, item, page));
                    }
                    section
                }

                Control::Number(number) => section.add(number_row(setting, number, page)),
                Control::Slider(config) => section.add(slider_row(setting, config, page)),
                Control::Text(field) => section.add(text_row(setting, field, page)),
            },
        };
    }

    section.into()
}

fn toggle<'a>(setting: &'a Setting, page: &'a Page) -> impl IntoListItem<'a, crate::pages::Message> {
    let is_on = current(setting, page)
        .and_then(store::as_bool)
        .unwrap_or(false);
    let (slot, entity) = (setting.slot, page.entity());

    labelled(setting).toggler(is_on, move |value| {
        Message::Toggle {
            page: entity,
            slot,
            value,
        }
        .into()
    })
}

/// A row that leaves Settings for a program the applet ships.
fn external<'a>(
    exec: &'a str,
    label: &'a str,
    page: &'a Page,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let entity = page.entity();
    let exec = exec.to_owned();

    settings::item::builder(label).control(
        widget::button::standard(fl!("applet-settings-open")).on_press(
            Message::Launch {
                page: entity,
                exec,
            }
            .into(),
        ),
    )
}

/// The entity of a page written in Rust, by the id it registered under.
fn find_page(
    binder: &page::Binder<crate::pages::Message>,
    id: &str,
) -> Option<page::Entity> {
    binder
        .info
        .iter()
        .find(|(_, info)| info.id == id)
        .map(|(entity, _)| entity)
}

/// An item builder carrying the setting's label and, if it has one, its description.
///
/// `Item::description` is generated by `derive_setters` with `strip_option`, so there is
/// no `_maybe` form to pass an `Option` to.
fn labelled(setting: &Setting) -> settings::item::Item<'_, crate::pages::Message> {
    let item = settings::item::builder(setting.label.as_str());

    match setting.description.as_deref() {
        Some(description) => item.description(description),
        None => item,
    }
}

fn heading(setting: &Setting) -> Element<'_, crate::pages::Message> {
    column::with_capacity(2)
        .spacing(2)
        .push(text::heading(setting.label.as_str()))
        .push_maybe(setting.description.as_deref().map(text::caption))
        .into()
}

fn choice_radio<'a>(
    setting: &'a Setting,
    items: &'a [ChoiceItem],
    index: usize,
    item: &'a ChoiceItem,
    page: &'a Page,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let (slot, entity) = (setting.slot, page.entity());

    settings::item::builder(item.label.as_str()).radio(
        index,
        selected(setting, items, page),
        move |item| {
            Message::Choose {
                page: entity,
                slot,
                item,
            }
            .into()
        },
    )
}

fn choice_dropdown<'a>(
    setting: &'a Setting,
    items: &'a [ChoiceItem],
    page: &'a Page,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let (slot, entity) = (setting.slot, page.entity());
    // Owned, not borrowed: `popup_dropdown` requires `S: 'static` because the popup
    // surface outlives this view.
    let labels: Vec<String> = items.iter().map(|item| item.label.clone()).collect();

    // `popup_dropdown`, not `dropdown`: the settings column is 800 points wide at most,
    // and a plain dropdown clips its list inside it.
    let control = dropdown::popup_dropdown(
        labels,
        selected(setting, items, page),
        move |item| {
            Message::Choose {
                page: entity,
                slot,
                item,
            }
            .into()
        },
        cosmic::iced::window::Id::RESERVED,
        |action| crate::pages::Message::AppletSettings(Message::Surface(action)),
        crate::app::Message::PageMessage,
    );

    labelled(setting).control(control)
}

fn number_row<'a>(
    setting: &'a Setting,
    number: &'a Number,
    page: &'a Page,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let (slot, entity) = (setting.slot, page.entity());
    let value = current_number(setting, page, number.optional);

    let spin = |value: f64| {
        widget::spin_button(
            display_number(value, number.decimals, number.suffix.as_deref()),
            setting.label.as_str(),
            value,
            number.step,
            number.min,
            number.max,
            move |value| {
                Message::Number {
                    page: entity,
                    slot,
                    value,
                }
                .into()
            },
        )
    };

    if !number.optional {
        return labelled(setting).control(spin(value.unwrap_or(number.min)));
    }

    // An optional key needs a way to say "no value at all", which a spin button bounded
    // by min and max cannot express. The toggle is that way, and the spin button only
    // appears once there is a number to adjust.
    let control = row::with_capacity(2)
        .spacing(theme::spacing().space_xs)
        .align_y(Alignment::Center)
        .push_maybe(value.map(|value| spin(value)))
        .push(
            toggler(value.is_some())
                .width(Length::Shrink)
                .on_toggle(move |enabled| {
                    Message::NumberEnabled {
                        page: entity,
                        slot,
                        enabled,
                    }
                    .into()
                }),
        );

    labelled(setting).control(control)
}

fn slider_row<'a>(
    setting: &'a Setting,
    config: &'a Slider,
    page: &'a Page,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let (slot, entity) = (setting.slot, page.entity());
    let value = current_number(setting, page, false).unwrap_or(config.min);

    // A bare slider stretches across the whole 800-point column and stops reading as a
    // control; upstream caps its sliders the same way.
    let control = row::with_capacity(3)
        .spacing(theme::spacing().space_xs)
        .align_y(Alignment::Center)
        .push_maybe(config.min_label.as_deref().map(text::caption))
        .push(
            slider(config.min..=config.max, value, move |value| {
                Message::Slide {
                    page: entity,
                    slot,
                    value,
                }
                .into()
            })
            .step(config.step)
            .width(Length::Fixed(250.0)),
        )
        .push_maybe(config.max_label.as_deref().map(text::caption));

    labelled(setting).flex_control(control)
}

fn text_row<'a>(
    setting: &'a Setting,
    field: &'a TextField,
    page: &'a Page,
) -> impl IntoListItem<'a, crate::pages::Message> + 'a {
    let (slot, entity) = (setting.slot, page.entity());
    let draft = page.draft(slot);

    // While editing, the field shows what has been typed; otherwise the stored value.
    // Keeping the two apart is what lets an abandoned edit leave the config alone.
    let shown = draft
        .map(str::to_owned)
        .or_else(|| current(setting, page).and_then(store::as_text))
        .unwrap_or_default();

    let control = widget::editable_input(
        field.placeholder.clone().unwrap_or_default(),
        shown,
        draft.is_some(),
        move |editing| {
            Message::TextEditing {
                page: entity,
                slot,
                editing,
            }
            .into()
        },
    )
    .on_input(move |text| {
        Message::TextDraft {
            page: entity,
            slot,
            text,
        }
        .into()
    })
    .on_submit(move |_| Message::TextCommit { page: entity, slot }.into())
    .on_unfocus(Message::TextCommit { page: entity, slot }.into())
    .width(Length::Fixed(200.0));

    labelled(setting).control(control)
}

/// The number shown on the spin button, with the unit the schema declared.
fn display_number(value: f64, decimals: u8, suffix: Option<&str>) -> String {
    let value = store::format_number(value, decimals);

    match suffix {
        Some(suffix) => format!("{value} {suffix}"),
        None => value,
    }
}

/// The value in force: what the config holds, else what the schema declares.
///
/// Falling back to the schema default matters on a machine where the applet has never
/// run and its package installed no defaults - without it every control would render
/// "off" while the applet itself uses something else.
fn current<'a>(setting: &'a Setting, page: &'a Page) -> Option<&'a str> {
    page.values()
        .get(setting.slot)
        .and_then(Option::as_deref)
        .or(setting.default.as_deref())
}

fn current_number(setting: &Setting, page: &Page, optional: bool) -> Option<f64> {
    let text = current(setting, page)?;

    if optional {
        store::as_optional_number(text).flatten()
    } else {
        store::as_number(text)
    }
}

/// Which option is in force, if any.
///
/// A value outside the schema's list selects nothing. That is deliberate: the applet
/// may accept more than the schema chose to expose, and quietly snapping the display to
/// the nearest listed option would misreport what is actually configured.
fn selected(setting: &Setting, items: &[ChoiceItem], page: &Page) -> Option<usize> {
    let value = current(setting, page)?;
    items
        .iter()
        .position(|item| store::same_value(&item.value, value))
}

/// A page body that says something instead of showing controls: an applet that ships no
/// schema, or one whose schema this build is too old to read.
///
/// Takes the text by value rather than by reference because the section closure that
/// calls it owns the string, and a view function may only borrow from its arguments.
pub fn message(text: String) -> Element<'static, crate::pages::Message> {
    text::body(text)
        .apply(cosmic::widget::container)
        .center_x(Length::Fill)
        .into()
}
